services:
  app:
    environment:
      - ENVIRONMENT=production
    build: .
    container_name: tunesplit_app
    ports:
      - "3003:3003"
    volumes:
      - models:/usr/src/app/pretrained_models
    restart: always

volumes:
  models:
    name: tunesplit_models