services:
  app:
    build:
      context: .
    image: rdelorenzo/tunesplit:dev
    environment:
      - ENVIRONMENT=development
    container_name: tunesplit_app
    ports:
      - "3003:3003"
    volumes:
      - models:/root/.cache/torch/hub/checkpoints
    restart: always

volumes:
  models:
    name: tunesplit_models