name: Docker + Node deploy

on:
  push:
    branches: [ master, cd ]


jobs:

  deploy:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Start docker compose
        run: docker compose up --build --detach
      - name: Check if online (60 secs max)
        run: wget --retry-connrefused --waitretry=5 --tries=6 localhost:3003