name: Docker + Node deploy

on:
  push:
    branches: [ main ]


jobs:

  deploy:

    permissions: write-all

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          minor-wording: 'feat'
          major-wording: 'MAJOR,cut-major,BREAKING,breaking'
          patch-wording: 'fix'     # Providing patch-wording will override commits
      - name: Start docker compose
        run: npm run docker-deploy
      - name: Check if online (15 tries with backoff)
        run: wget --retry-connrefused --tries=15 --spider localhost:3003