name: Docker + Node deploy

on:
  push:
    branches: [ master, cd ]


jobs:

  deploy:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Start docker compose
        run: docker compose up --build --detach
      - name: Wait for server to start up
        run: sleep 10
      - name: Check if online
        run: curl localhost:3003