name: Docker + Node deploy

on:
  push:
    branches: [ main ]


jobs:

  deploy:

    permissions: write-all

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        run: node ci/bumpVersion.js
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Start docker compose
        run: npm run docker-deploy
      - name: Add & push versioned image tags
        run: node ci/addDockerVersionTag.js
#      - name: Publish docker image
#        run: docker compose push
      - name: Check if online (15 tries with backoff)
        run: wget --retry-connrefused --tries=15 --spider localhost:3003